### PR TITLE
Key Error: "u'items'" #87 fix

### PR DESCRIPTION
**Pull request by tfilo**
Hello, since youtube search doesn't work with original API key, I did this change to be able provide my personal API key from configuration. If you like you can merge this fix, but from than it will be needed for every user to provide their API key. But I left original API key as default configuration so if this API key starts work again it can work with it.

### CODE REVIEW

**Comment by tfilo** [comment]
Don't try to use own API key, it can lead to ban on your google account.

**Comment by kingosticks** [comment]
Strictly speaking, yes, but it's very unlikely. You can always make a
secondary Google account for this purpose.

**Comment by tfilo** [comment]
I don't know how google act at this, but since dz0ny has his account suspended. I will wait for more information from him. Secondary account sounds good but can't suspending one account influence your other accounts ? Since it can be easy for google to determine all accounts of one person. It's not problem to reopen RP #89 but as dz0ny said, how can we guarantee that users won't have their account under suspension/review.

**Comment by kingosticks** [comment]
I think the "everyone is doing it" rule applies here but I understand your concern. I still think your PR is worth merging, at least people have the choice.

**Pull request closed without merging**
